plugins {
    id 'java'
    id 'application'
    id 'com.palantir.git-version' version '5.1.0'
}

version = gitVersion()

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

application {
    mainClass = 'it.lapo.jtlsdoctor.Main'
}

jar {
    manifest {
        attributes 'Main-Class': 'it.lapo.jtlsdoctor.Main'
        attributes 'Implementation-Title': project.name
        attributes 'Implementation-Version': project.version
    }
}
