plugins {
    id 'java'
    id 'application'
}

version = '0.1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

application {
    mainClass = 'it.lapo.jtlsdoctor.Main'
}

jar {
    manifest {
        attributes 'Main-Class': 'it.lapo.jtlsdoctor.Main'
        attributes 'Implementation-Title': project.name
        attributes 'Implementation-Version': project.version
    }
}
